# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('aka', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('stream_url', models.CharField(max_length=100)),
                ('artwork_url', models.CharField(max_length=100)),
                ('waveform_url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('artist_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MixtapePlatform.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profile_url', models.CharField(max_length=100)),
                ('thumbnail_url', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='user_info_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MixtapePlatform.User'),
        ),
    ]
