# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('aka', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('stream_url', models.CharField(max_length=100)),
                ('artwork_url', models.CharField(max_length=100)),
                ('waveform_url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('sc_id', models.CharField(max_length=100)),
                ('audio_info_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MixtapePlatform.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('chart_type', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChartRanking',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('chart_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartRanking_fk', to='MixtapePlatform.Chart')),
            ],
        ),
        migrations.CreateModel(
            name='Mixtape',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('voice_url', models.CharField(max_length=100)),
                ('lyrics', models.CharField(max_length=2048)),
                ('artist_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Audio_fk', to='MixtapePlatform.Artist')),
                ('audio_info_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MixtapePlatform.Audio')),
                ('original_beat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MixtapePlatform.Beat')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('audio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_fk', to='MixtapePlatform.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profile_url', models.CharField(max_length=100)),
                ('thumbnail_url', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('artist_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFollow_fk', to='MixtapePlatform.Artist')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFollow_fk', to='MixtapePlatform.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('audio_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userLike_fk', to='MixtapePlatform.Audio')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userLike_fk', to='MixtapePlatform.User')),
            ],
        ),
        migrations.AddField(
            model_name='chartranking',
            name='ranking_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartRanking_fk', to='MixtapePlatform.Ranking'),
        ),
        migrations.AddField(
            model_name='artist',
            name='user_info_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_fk', to='MixtapePlatform.User'),
        ),
    ]
