# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MixtapePlatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartranking',
            name='chart_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartRanking_fk', to='MixtapePlatform.Chart'),
        ),
        migrations.AlterField(
            model_name='chartranking',
            name='ranking_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartRanking_fk', to='MixtapePlatform.Ranking'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='audio_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_fk', to='MixtapePlatform.Audio'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='artist_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFollow_fk', to='MixtapePlatform.Artist'),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFollow_fk', to='MixtapePlatform.User'),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='audio_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userLike_fk', to='MixtapePlatform.Audio'),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userLike_fk', to='MixtapePlatform.User'),
        ),
    ]
