# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MixtapePlatform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beat',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('audio_info_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MixtapePlatform.Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('chart_type', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChartRanking',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('chart_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MixtapePlatform.Chart')),
            ],
        ),
        migrations.CreateModel(
            name='Mixtape',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('voice_url', models.CharField(max_length=100)),
                ('lyrics', models.CharField(max_length=2048)),
                ('audio_info_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MixtapePlatform.Audio')),
                ('original_beat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MixtapePlatform.Beat')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('sequence', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('audio_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MixtapePlatform.Audio')),
            ],
        ),
        migrations.AddField(
            model_name='chartranking',
            name='ranking_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MixtapePlatform.Ranking'),
        ),
    ]
