# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MixtapePlatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='artist',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='audio',
            name='like_cnt',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='audio',
            name='title',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
