# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MixtapePlatform', '0002_auto_20161212_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beat',
            old_name='audio_info_fk',
            new_name='audio_info',
        ),
        migrations.RenameField(
            model_name='mixtape',
            old_name='audio_info_fk',
            new_name='audio_info',
        ),
    ]
