# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MixtapePlatform', '0002_auto_20161211_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='artist_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Audio_fk', to='MixtapePlatform.Artist'),
        ),
    ]
